import type { Metadata } from "next";
import { Lato } from "next/font/google";
import { Provider } from "@/components/ui/provider";
import Navbar from "@/components/navbar";
import Footer from "@/sections/footer";
import { Box } from "@chakra-ui/react";

const lato = Lato({
  variable: "--font-lato",
  weight: ['100', '300', '400', '700', '900'],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lato.variable}`}>
        <Provider>
          <Box bg="white" h={'fit-content'} px={{ base: 4, sm: 8, md: 12, xl: 28 }}>
            <Navbar />
            {children}
            <Footer />
          </Box>
        </Provider>
      </body>
    </html>
  );
}
